version: 2
jobs:
  run_build:
    docker:
      - image: circleci/node:6.11.2
    working_directory: ~/tmp
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ~/tmp
          paths: .

  run_tests:
    docker:
      - image: circleci/node:6.11.2
    working_directory: ~/tmp
    steps:
      - attach_workspace:
          at: ~/tmp
      - run: npm run lint

  deploy_production:
    docker:
      - image: circleci/node:6.11.2
    working_directory: ~/tmp
    steps:
      - checkout
      - attach_workspace:
          at: ~/loot
      - run: ssh-keyscan 138.68.174.154 >> ~/.ssh/known_hosts
      - run: ssh pedro@138.68.174.154 "cd apps/charisma-app && git checkout production && git pull && npm run deploy"

workflows:
  version: 2
  build:
    jobs:
      - run_build
      - run_tests:
          requires:
            - run_build
      - deploy_production:
          requires:
            - run_build
            - run_tests
          filters:
            branches:
              only: production
